### ISSUE TITLE
[Boss]: Sartharion Spawns Too Many Adds

### ISSUE THREAD

**Issue by Zerixx** [FeenixServerProject/Wrath_3.3.5_Issue_tracker#1]
## Description

Currently, Sartharion spawns too many flame adds from the vortexes. Or so we believe.

**Comment by deathstreal** [comment]
Sartharion's Fire elemental Adds

    Health: 65165 (25), ~26,000 (10) 

These adds are summoned every ?s in groups of 2-4 to be offtanked.

http://wowwiki.wikia.com/wiki/Sartharion

**Comment by Zerixx** [comment]
After MUCH review, and testing, this is working as intended. Lava Blazes need dedicated DPS to tackle. This is one of the things that makes 10m Sarth difficult. 

I checked the strats and the code multiple times and everything seems right. We'll review this further when raids start.
