### ISSUE TITLE
Hunter traps

### ISSUE THREAD

**Issue by Cookiemonster94** [FeenixServerProject/Wrath_3.3.5_Issue_tracker#100]
Hey!

Having some trouble with hunter traps. Ice traps are working, but fire and snake traps do not go off when triggered by mobs. This needs to be fixed, please! :)

**Comment by gianclaudio-giordano** [comment]
Confirmed, chronologically occurred after Patch 2.5 if this might help tracking down the source of the issue.

Explosive trap - **not triggered**
Immolation trap - **triggered**
Ice/Frost trap - **triggered**
Snake Trap - **not triggered** (and obviously it doesnt cause Entrapment)

**Comment by gianclaudio-giordano** [comment]
Evidences: 

Ice trap + Snake trap: **https://youtu.be/P33fxsTp0nQ**
Immolation trap + Explosive trap: **https://youtu.be/NHRGa117CNs**

**Comment by sionwilliams** [comment]
These are bugged yes, sort your stuff out Feenix!

**Comment by Zerixx** [comment]
@sionwilliams Thanks for asking nicely. I already know about the bug, and am working on it :)

**Comment by Cookiemonster94** [comment]
How's the progress in fixing the bug going ? :)

**Comment by gianclaudio-giordano** [comment]
Yes please! Sorry about Sions manners being a bit harsh, at this moment hunter has several disadvantages when kiting melees with Entrapment half working and concussive barrage not triggering (see other issue for more infos)

**Comment by Zerixx** [comment]
Fixed @Cookiemonster94  @jancloud -- queued for live hotfix.
