### ISSUE TITLE
Multiple Sparksocket Minefield Land Mine explosions incorrectly trigger anticheat system

### ISSUE THREAD

**Issue by corcaroli** [FeenixServerProject/Wrath_3.3.5_Issue_tracker#101]
Achievement [Mine Sweeper] (Get caught in 10 consecutive land mine explosions in the Sparksocket Minefield without landing.) is very hard to obtain because of the anticheat system. Being caught in multiple Land Mine explosions in a short time span incorrectly triggers the anticheat system, because those mines send an unlucky player flying. The achievement itself isn't that hard to get, but this anticheat interruptions are annoying.

**Comment by Zerixx** [comment]
Fixed on Raid Test with new Anticheat. Closing this issue.
