### ISSUE TITLE
Hunter talent "Concussive Barrage" not working.

### ISSUE THREAD

**Issue by gianclaudio-giordano** [FeenixServerProject/Wrath_3.3.5_Issue_tracker#103]
Report ID: **DIO001**
Reporter Name: **Dioporc**
Date/Time: **Feb 15th 2017, 16:12 gmt+1**
Error Severity: **Average**
Zone/Instance: **Everywhere**
What type of error occurred?: **Talent does not work**
What was the actual result vs. the expected result?: **The talent "Concussive Barrage" in the Marksmanship tree is supposed to daze target(s) hit by Multi-shot or Chimera Shot. It does not daze at all.**
Can the error be repeated? If so, what are the steps?: **Create hunter, spec 1/2 or 2/2 "concussive barrage", hit any target with either Multi or Chimera shots**
Link to Video Evidence: **https://youtu.be/NHRGa117CNs**
External/Related Links: N/A
Please detail your character’s race, class, and items (optional): **Orc Hunter**

**Comment by sionwilliams** [comment]
This is true. its bugged asf.

**Comment by Zerixx** [comment]
Fixed
