### ISSUE TITLE
Glory of the raider 10/25 no mount rewards

### ISSUE THREAD

**Issue by kauski** [FeenixServerProject/Wrath_3.3.5_Issue_tracker#104]
Atleast not showin on the rewards for receivin that archievement

http://www.wowhead.com/achievement=2138/glory-of-the-raider-25-player
http://www.wowhead.com/achievement=2137/glory-of-the-raider-10-player

Both archievements rewarded a proto dragon upon completion before ulduar was released.

Since ulduar isnt on the server yet, we should have the mounts as rewards for doing those archievements.

As pvp (arena) players do get seasonal rewards from those seasons that were not avaiable in 3.3.5 its only fair that pve players get their rewards aswell from their archievements.

http://www.wowhead.com/item=44164/reins-of-the-black-proto-drake#teaches-ability
http://www.wowhead.com/item=44175/reins-of-the-plagued-proto-drake#contained-in-item

**Comment by corcaroli** [comment]
From what @Zerixx says [here](https://github.com/FeenixServerProject/Wrath_3.3.5_Issue_tracker/issues/68) I can assume that it's not possible to add back these two reward mounts back into the game, for we're using 3.3.5a clients and they were removed in 3.1.0 update. A confirmation would be nice to get though.
And a tip for future: try checking closed issues for duplicates before opening a new one. :-D

**Comment by kauski** [comment]
okhay, i assume then there will be no arena rewards either anymore that were not possible to archieve at 3.3.5 patch.
