### ISSUE TITLE
Zombiefest!/Arthas in general

### ISSUE THREAD

**Issue by Qvistt** [FeenixServerProject/Wrath_3.3.5_Issue_tracker#105]
Achievement Zombiefest! in CoS Hardly doable/undoable due to lack of zombie spawns on upper floor after doing the proper tactic for it. Should be around 80-85 zombies respawned on upper floor we managed to get 16.

Probably due to arthas being generally bugged and oneshots everything with instant exorcism's without gcd. Whenever he runs around killing zombies we get no credit. He also attacks anything near him even if we havent spoken to him yet while downstairs. 

Solution: Fix arthas or just have him do no spells whatsoever.

**Comment by Zerixx** [comment]
Fixed on prelive.
