### ISSUE TITLE
Gluth 10man Adds spawns incorrectly

### ISSUE THREAD

**Issue by Qvistt** [FeenixServerProject/Wrath_3.3.5_Issue_tracker#106]
Gluth 10man Zombie adds spawns as 25man version.

They're supposed to spawn only in the middle in 10man so you can solokite them easily 
like shown here - https://www.youtube.com/watch?v=lSPCiVq2668

Instead they spawn on all 3 spawnpoints just like in 25man wich makes it alot harder for solokiters and therefor raids having to waste a player to help kite.

**Comment by corcaroli** [comment]
Even if it is a bug or whatever I'd advise against fixing it. Naxxramas is too easy in general, so this issue at least adds some challenge. And to be honest, it's not hard to kill the boss within the enrage timer with 2 kiters instead of 1. :d

**Comment by Qvistt** [comment]
yea not saying its hard but a bug is a bug don't you think? :) if we want a good server we'd want everything to work correctly

**Comment by lajhar** [comment]
Issue confirmed.
Zombie Chows (16360) should spawn only from the middle pit in 10-man version.
Currently they're spawning randomly from all the 3 pits.
