### ISSUE TITLE
[Raid] Gluth's Decimate reduces players' health to 50% instead of 5%

### ISSUE THREAD

**Issue by corcaroli** [FeenixServerProject/Wrath_3.3.5_Issue_tracker#107]
It's weird that noone has reported this yet.
There isn't much to add to the title. Decimate is supposed to reduce both players' and zombies' health to the 5% of their maximums, but for some reason it reduces player's health only to 50%. It works correctly on zombies though.

**Comment by lajhar** [comment]
Can't confirm the issue, it is working as intended on the PTR.
