### ISSUE TITLE
Bone Shield charges triggers too fast.

### ISSUE THREAD

**Issue by fyrinx** [FeenixServerProject/Wrath_3.3.5_Issue_tracker#108]
As the description goes: 

The Death Knight is surrounded by 3 whirling bones. While at least 1 bone remains, Ghe:she; takes 20% less damage from all sources and deals 2% more damage with all attacks, spells and abilities. Each damaging attack that lands consumes 1 bone. Lasts 5 min.

Bone Shield works in terms of description, but each trigger is supposed to have an internal cooldown on 2 seconds, that is according to what is seen from a [ tank pov from retail](https://www.youtube.com/watch?v=oMD01698e7E)  (you notice at 4:25 and at about 6:00 the charges dont down faster than 2 secs per charge) and in a tanking guide from tank spot which states it.

**Comment by dangreenberggit** [comment]
Additional evidence: [WoWWiki](http://wowwiki.wikia.com/wiki/Bone_Shield) indicates in patch changes that Bone Shield Charges could only be consumed at a rate of one charge every 2 seconds until Patch 6.0.2.

**Comment by lajhar** [comment]
Issue confirmed.

The 2 sec internal cooldown is missing, thus charges getting consumed too fast.
