### ISSUE TITLE
 [Jewelcrafting: Bold Cardinal Ruby]

### ISSUE THREAD

**Issue by Holmenros** [FeenixServerProject/Wrath_3.3.5_Issue_tracker#112]
[Jewelcrafting: Bold Cardinal Ruby] is not available to buy from Timothy Jones in Dalaran.

Added in patch 3.0.1.8634

Regards Holmes

**Comment by corcaroli** [comment]
http://www.wowhead.com/item=46917/design-bold-cardinal-ruby
> Added in patch 3.2.0.10026

**Comment by Holmenros** [comment]
http://www.wowhead.com/item=40111/bold-cardinal-ruby#comments

**Comment by corcaroli** [comment]
You've just [confirmed](http://www.wowhead.com/item=40111/bold-cardinal-ruby#comments:id=749895) it.
Anyway, all the epic Norhtrend gems were introduced in the patch 3.2.0(except Stormjewels from the fishing dailies, which came in 3.1.0). I [have reported](https://github.com/FeenixServerProject/Wrath_3.3.5_Issue_tracker/issues/76) that issue already.

**Comment by Zerixx** [comment]
Duplicate. We know :)
