### ISSUE TITLE
Titansteel bar doesn't have a cooldown

### ISSUE THREAD

**Issue by corcaroli** [FeenixServerProject/Wrath_3.3.5_Issue_tracker#113]
Prior to patch 3.3.3, smelting Titansteel bars had a cooldown of 20 hours. But since the current content is not even 3.1, you might want to fix this, Although i'm not sure if it's possible to change that, since it seems to me like a client side feature. But i'm reporting this issue anyway. 8)

**Comment by Zerixx** [comment]
We can't fix this. Spell changed, not much we can do :(
