### ISSUE TITLE
Eye of Eternity(25 man) grants wrong emblems on killing Malygos

### ISSUE THREAD

**Issue by corcaroli** [FeenixServerProject/Wrath_3.3.5_Issue_tracker#114]
Upon killing Malygos in 25 man version of Eye of Eternity and looting the chest (or whatever that thing is) raid members get Emblems of Heroism instead of Emblems of Valor, as from any other currently available 25 man raid boss.

**Comment by deathstreal** [comment]
This is probably a Zerix spaghetti, as EoE 10 awards 2 Emblems of Valor.

**Comment by Zerixx** [comment]
Fixed on PreLive.
