### ISSUE TITLE
[Utgarde Keep] Wrong loot table for trash mobs.

### ISSUE THREAD

**Issue by Viikate** [FeenixServerProject/Wrath_3.3.5_Issue_tracker#116]
In Utgarde keep Heroic version the trash mobs should drop Tattered Castle Drape and Runecaster's Matle among other uncommon items, instead they drop normal mode loot such as Vrykul Shackles, Skein Woven Mantle and lvl 67-70 uncommon items.

**Comment by Zerixx** [comment]
Fixed on PreLive.
