### ISSUE TITLE
warlock [conflagrate]

### ISSUE THREAD

**Issue by teddys** [FeenixServerProject/Wrath_3.3.5_Issue_tracker#118]
does not become available to use immediately after immolate is up on a target, but rather with 0,2-1 sec delay

it's really triggering

**Comment by lajhar** [comment]
Issue confirmed, you cannot consume the DoT effect of Immolate (max rank: 47811) by using Conflagrate (17962) immediately, you need to wait ~ 0,5 sec to be able to do it.
Picture of combat log added
![image](https://cloud.githubusercontent.com/assets/20255946/23125702/679c830c-f773-11e6-80a8-779753458a6f.png)

**Comment by Zerixx** [comment]
https://eu.battle.net/forums/en/wow/topic/2723297471
https://eu.battle.net/forums/en/wow/topic/7527663253

I researched this a lot. Conflag should have a 700ms delay form triggering after casting immolate or shadowflame. Closing this up.

**Comment by teddys** [comment]
Been playing this game for 10 years and I've never seen this delay anywhere, so I the fact that it might be blizzlike didn't cross my mind at all. That's actually retarded. Anyways sorry for not googling this first.

**Comment by Zerixx** [comment]
@teddys It's really not a problem. I was confused by it, too.
