### ISSUE TITLE
Malygos 25M dropping T7.5 Items 

### ISSUE THREAD

**Issue by deathstreal** [FeenixServerProject/Wrath_3.3.5_Issue_tracker#119]
So, Malygos dropped a T7.5 item today, just like they drop in VoA. I am 99% sure this is not supposed to happen after checking 3 sources and my own memory. Unfortunately, I forgot to take a screenshot. The item can be found on Nagge (Arms Warrior) who got the T7.5 Protection Warrior Legs (the tier item that dropped) for offspec.

**Comment by dangreenberggit** [comment]
Addition: AFAIK the boss only drops prot warrior token pants.

**Comment by Zerixx** [comment]
Fixed on PreLive.
