### ISSUE TITLE
Righteous Fury dropping off when dying

### ISSUE THREAD

**Issue by deathstreal** [FeenixServerProject/Wrath_3.3.5_Issue_tracker#120]
Righteous Fury was changed in WotLK, becoming an Aura-like ability. Unless deactivated or changing spec, it should remain active.
Right now, it will drop off everytime you die, sometimes resulting in awkward situations.

**Comment by corcaroli** [comment]
http://wowwiki.wikia.com/wiki/Righteous_Fury
> Patch 3.2.0 (04-Aug-2009): No longer has a duration, remaining until cancelled **or death**. Also cancelled when a Paladin activates a different talent specialization.

>  **Patch 4.1.0** (26-Apr-2011): Righteous Fury now persists through death.

**Comment by Qingle** [comment]
as @corcaroli said
