### ISSUE TITLE
Achievements [Looking For More], [Looking For Many], [Looking For Multitudes] stopped working

### ISSUE THREAD

**Issue by corcaroli** [FeenixServerProject/Wrath_3.3.5_Issue_tracker#122]
After one of the updates, I don't know which exactly, counters of mentioned achievements simply stopped increasing. This was checked just today on a freshly geared 80 toon.

**Comment by Zerixx** [comment]
Technically, these didn't exist until dungeon finder. 3.2? They'll be enabled again eventually ^^

**Comment by corcaroli** [comment]
Why won't you just disable the dungeon finder then? D-:

**Comment by Zerixx** [comment]
I wanted to :( but a vote was not in my favor. No biggie.
