### ISSUE TITLE
Talent builds cannot be viewed upon inspecting

### ISSUE THREAD

**Issue by corcaroli** [FeenixServerProject/Wrath_3.3.5_Issue_tracker#123]
All one can see upon inspecting anybody's talents is that all three trees seem to be completely grey, as if no talents were picked at all. Clearing cache and disabling all the addons (together) doesn't help. Not sure if this can really be fixed but asking for assistance anyway. :d

**Comment by Zerixx** [comment]
Ahh, I almost forgot. I'll fix this in a bit.
