### ISSUE TITLE
Ulduar 25 Thorim normal Dark Rune Champions

### ISSUE THREAD

**Issue by Seethatburst** [FeenixServerProject/Wrath_3.3.5_Issue_tracker#126]
Issue=Dark Rune Champions are immune to disarm
How it should work="The most dangerous mobs are the Dark Rune Champions which do a whirlwind attack. They need to be kept away from the main raid, and/or disarmed" source=http://wowwiki.wikia.com/wiki/Thorim_(tactics)
How to reproduce=Engage Thorim in phase 1 and try to disarm any Champion.

**Comment by Zerixx** [comment]
@Seethatburst Mind sending me the NPC Id or wowhead link?

**Comment by Seethatburst** [comment]
http://www.wowhead.com/npc=32876/dark-rune-champion#abilities

**Comment by Zerixx** [comment]
@devastator Need immunity mask for disarm fixed.
