### ISSUE TITLE
Can't inspect talents

### ISSUE THREAD

**Issue by fyrinx** [FeenixServerProject/Wrath_3.3.5_Issue_tracker#128]
Hello. 

As this is one bug I assume all players know of, it would be nice to have it fixed soon.

The inspect function doesn't allow players to inspect the talents (specs) of an other player. This could potentially help people prevent a disasterous raid.

**Comment by corcaroli** [comment]
That's a duplicate of #123 :P

**Comment by fyrinx** [comment]
Damn, couldn't find it before I posted it. :p
