### ISSUE TITLE
Farseer Eannu is missing from Ironforge

### ISSUE THREAD

**Issue by phreaque** [FeenixServerProject/Wrath_3.3.5_Issue_tracker#129]
The npc "Farseer Eannu" is missing
http://www.wowhead.com/npc=35073/farseer-eannu
He should be standing near the shaman trainer in Ironforge
He is needed for the shaman quest  "Relic of the Earthen Ring (alliance)"
http://www.wowhead.com/quest=14111/relic-of-the-earthen-ring

**Comment by Zerixx** [comment]
Duplicate. Already stated this content comes with 3.3.5a
