### ISSUE TITLE
Quest mob hitting too hard?

### ISSUE THREAD

**Issue by Flufflylolqt** [FeenixServerProject/Wrath_3.3.5_Issue_tracker#13]
http://www.wowhead.com/quest=12897/if-he-cannot-be-turned

He 2shots the allies u get

**Comment by lajhar** [comment]
The NPC does not hit hard at all, he is a level 80 elite creature, and hits 3-5k to a player with 0 armor.
You should pull him and let the allies hit him from behind, so they won't get 2 shoted by his cleave ability.
