### ISSUE TITLE
The Eye of Eternity, opposite emblems drop.

### ISSUE THREAD

**Issue by Donlund** [FeenixServerProject/Wrath_3.3.5_Issue_tracker#135]
(looked around in bug tracker since I assumed this issue was posted long time ago, but apparently it wasnt or my looking skills are shit)

As the title says the different difficulties of Malygos drops "opposite" emblems of what I believe they are supposed to.

Currently 10m EoE drops 2x Valor Emblems while 25m EoE drops 2x Heroism Emblems.

To the best of my knowledge, its supposed to be the other way around.

**Comment by corcaroli** [comment]
You should check closed issues as well. #114

**Comment by Donlund** [comment]
Ah rip, I even did first and missed it. My apologies.
