### ISSUE TITLE
Some seasonal events are missing in the in-game calendar

### ISSUE THREAD

**Issue by corcaroli** [FeenixServerProject/Wrath_3.3.5_Issue_tracker#137]
Some seasonal events(mostly from the first year half) are not shown on the in-game calendar. While Midsummer Festival, Pirates' day, Brewfest, Hallow's end, Day of the Dead and Feas of Winter Veil are present there, such events as Children's Week, Harvest Festival, Love is in the Air, Lunar Festival, Noblegarden, Pilgrim's Bounty are absent. (There might have been more, but i don't remember them all well.)

**Comment by Zerixx** [comment]
If I recall correctly, seasonal events will be in the calendar come 3.3.5

**Comment by corcaroli** [comment]
Fine (not really), but could we at least have another way to track when these events start and, more importantly, end? Those dates are not the same as on the wowwiki(say, compare this year's Lunar Festival dates [on wowwiki](http://wowwiki.wikia.com/wiki/Lunar_Festival) and at our server), and most likely on other (semi)official websites as well.

**Comment by Zerixx** [comment]
I have the dates in a database. Perhaps I can try to give a good time table.
