### ISSUE TITLE
Azjol Nerub.

### ISSUE THREAD

**Issue by Flufflylolqt** [FeenixServerProject/Wrath_3.3.5_Issue_tracker#14]
Hadronox adds are spawning constantly, and fast. they literaly wont stop spawning

**Comment by lajhar** [comment]
Issue confirmed, too many ads spawn during the encounter, making the fight "impossible" due to the health gain from Nerubians.

**Comment by Zerixx** [comment]
We ran this the other day and this is working as intended.
