### ISSUE TITLE
Arena Team Starting Rating

### ISSUE THREAD

**Issue by Bellzubab** [FeenixServerProject/Wrath_3.3.5_Issue_tracker#143]
Teams start at 0 rating on RoS. However, during Arena Season 5, teams started at 1500. Hateful/Deadly items have such a high rating requirement to reflect this higher starting rating.

"Arena Season 6 (Furious) began on April 21, 2009 with the release of Patch 3.1.0 and ended on August, 2009. This was the first season where arena teams started at 0 rating instead of 1500." (per http://wow.gamepedia.com/Season_6)

"As of Season 6 and later, the arena system was changed so that new teams start with a rating of 0 rather than 1500." (per http://wowwiki.wikia.com/wiki/Arena_point)

Hateful/Deadly is much harder to obtain because of this bug, because you have to win at least a few dozen arenas to make it back to 1500 rating, which is where you should initially start anyway. This greatly affects your MMR, which means you'll get less rating from teams.

If this cannot be fixed because teams have already been created (which doesn't really make sense, as teams lower than 1500 would just remake their teams, and teams above 1500 would just keep theirs), that would be somewhat understandable. However, if you do not fix this bug, you absolutely need to fix Arena Point Calculation.

**Comment by Zerixx** [comment]
Patch 3.1/Ulduar is coming very soon, which is why I haven't made any changes to this.

**Comment by Bellzubab** [comment]
Uh, then Season 5 will only be 1 month long on RoS? That can't be right...
