### ISSUE TITLE
Arena Point Calculation

### ISSUE THREAD

**Issue by Bellzubab** [FeenixServerProject/Wrath_3.3.5_Issue_tracker#144]
Currently RoS is using the same arena point formula as the TBC realms. In WotLK, it was implemented that for every arena flush teams would receive a minimum value of points equivalent to what they would get at 1500 rating. This floor value for 2v2 is 261 arena points. If your team is at 0 rating and qualifies for arena points, you should get 261 arena points. If your team is at 1499, you should get 261 arena points. If your team is at 1500, you should get 261 arena points.

"As of Season 6 and later, the arena system was changed so that new teams start with a rating of 0 rather than 1500. Consequently, the formula was changed so that all teams below 1500 rating will earn points as if they were a 1500 rated team." (per http://wowwiki.wikia.com/wiki/Arena_point).

Moreover, check out any WotLK arena point calculator site. (take your pick from http://wowwiki.wikia.com/wiki/Arena_point_calculator)

This is only an issue because teams start at 0 rating instead of 1500, which is a bug in S5. If you fix one of these two bugs, the other isn't as terrible. But with both of them broken, it's completely gamebreaking to any arena players looking to gear up.

**Comment by Zerixx** [comment]
Patch 3.1/Ulduar is coming very soon, which is why I haven't made any changes to this.

**Comment by Bellzubab** [comment]
This will need to be changed for Season 6.

I believe simply changing the current arena season in worldserver.conf to 6 *should* fix this, if ArenaTeam.cpp is the same (specifically the parts about calculating arena points, starting at line 593) as stock Trinity.
