### ISSUE TITLE
[Jewelcrafting] Shifting Twilight Opal recipe missing

### ISSUE THREAD

**Issue by niggerious** [FeenixServerProject/Wrath_3.3.5_Issue_tracker#147]
Shifting Twilight Opal recipe is missing from Tiffany Cartier.

**Comment by corcaroli** [comment]
[You'll have to wait for the Ulduar release](http://wowwiki.wikia.com/wiki/Shifting_Twilight_Opal):
> Patch 3.1.0 (14-Apr-2009): Added.

**Comment by Zerixx** [comment]
^
