### ISSUE TITLE
Eye of the Storm scoreboard vs map discrepancy

### ISSUE THREAD

**Issue by Bellzubab** [FeenixServerProject/Wrath_3.3.5_Issue_tracker#153]
https://puu.sh/uBgWW/dfa144bfed.jpg

Map shows 3 Horde bases and 1 Ally base, scoreboard shows 2/2.

From what I can tell, scoreboard is correct.

Kinda hard to win a BG when you don't know which bases you have.

**Comment by Zerixx** [comment]
I have actually seen these bugs myself on Blizzard servers. Nothing we can do about it.

**Comment by Bellzubab** [comment]
I have to disagree. It was happening frequently, not just a one time thing.

There are other servers where I've never seen this happen, so I'm going to have to assume it's something on Feenix's end.

I wouldn't bother reporting something that is a one-in-a-million edge case and can't be replicated; that'd be a waste of developer time.
