### ISSUE TITLE
Sons of Hodir questchain rep didn't work

### ISSUE THREAD

**Issue by Nuckels** [FeenixServerProject/Wrath_3.3.5_Issue_tracker#156]
Hello everyone. My issue is simple, i did all the pre-quests for the Sons of Hodir rep, which are supposed to get a player to normal rep, yet i have no other quests to do, and i'm stuck at hated, precisely at 26400/36000. I made a ticket and was told to clear Cache and WTF, and if it wouldn't work to make a post here at the issue tracker. Well apparently WTF-Cache didn't work so here i am. 
Char name: Nuckels
Faction: Alliance
Realm: Shadows
Thanks in advance.

**Comment by Bellzubab** [comment]
You have to do a few more quests in the chain. I had this issue and was pretty upset by it, but ended up figuring it out.
