### ISSUE TITLE
False anticheat system alarms

### ISSUE THREAD

**Issue by corcaroli** [FeenixServerProject/Wrath_3.3.5_Issue_tracker#157]
As you know, current anticheat system isn't perfect. Several issues have been addressed and fixed already, but there are still more. Here is a couple of them.

- The system triggers if a player riding a flying mount gets buffed with priests' Levitate, and the flying player gets kicked. (Mages' Slow Fall is all right, just checked that with a guildie.)
- The system triggers if a player controlling a Steam Tonk makes it jump while using its ability Nitrous Boost, and the Tonk's owner gets kicked. (This seems somewhat random - the other time I tried to check this, I was jumping with my Tonk constantly with that boost on, and couldn't trigger the anticheat for ~15 seconds; but sometimes it would trigger after ~5 seconds of jumping.)

**Comment by Zerixx** [comment]
Just wait for an hour or two :)

**Comment by Bellzubab** [comment]
Dang. Zerixx beat me by a minute. Needs to be fixed for Rocket Boots malfunctioning too. Really disheartening when you get kicked out of a BG/WG because of that.

**Comment by corcaroli** [comment]
Will the Steam Tonk issue be fixed as well? I want to have some fun battles with friends! :-D

**Comment by Zerixx** [comment]
Yes it will all be fixed :)
