### ISSUE TITLE
Can't use same type of glyph on different specialization pages

### ISSUE THREAD

**Issue by Novallia** [FeenixServerProject/Wrath_3.3.5_Issue_tracker#161]
I've encountered this problem a few days ago when I bought the dual talent tree on my Death Knight.
I wanted to use Glyph of Disease in both talent specs, yet I seen an error message when trying to bind it  to the spec it wasn't bound on.

I plaed on Retail back then and I rmemeber binding Glyph of Judgement on both of my pages without any problem.
Also I checked wowwikki and it mentions nothing about not being able to use the saem type of glyph on different pages: http://wowwiki.wikia.com/wiki/Dual_Talent_Specialization

Here is a video of the issue: https://youtu.be/GtFe_TwQ1Mg
It is obvious I was trying to activate it on a different page, the one tha twas active in that moment.

To be honest I am not sure if it is a bug of the glyphs since it says nowere that they are unique or if it si a bug of dual talent specialisation or a problem of the rune pages.

Thank you for your timr
Looking forward for an answer

Edit: It seems to be functioning now. Sorry for wasting your time!

**Comment by dangreenberggit** [comment]
As far as I know, the same glyph is unable to be applied in both specs in one-login session, but the issue is overcome by relogging.

**Comment by Novallia** [comment]
Resolved the problem. Thanks alot!
