### ISSUE TITLE
Anti-Cheat is useless atm

### ISSUE THREAD

**Issue by Dakyo** [FeenixServerProject/Wrath_3.3.5_Issue_tracker#164]
yo, can you disable this Anti-Cheat System until you get it figured out and working properly? as it stands right now when getting deathgripped, the server thinks you're moving too fast and it makes you get stuck mid-air, with no possible way of getting down. Same thing also applies if you get weird Death Coil or Fear pathing, it just freezes you in place.

**Comment by Bellzubab** [comment]
"Useless" is a bit much. It's better than it was, but still has a LOT of kinks to be worked out.

**Comment by Zerixx** [comment]
Well, would you rather get kicked out of game randomly for no reason? To call it useless is a bit excessive. Obviously, when new systems roll out, there are things that need tweaked and hotfixed, and they will happen in time.

**Comment by Dakyo** [comment]
I understand that, but don't you think they should have at least set the max speed a little bit higher than the Deathgrip speed?

**Comment by Zerixx** [comment]
@Dakyo Latency affects all of them. That means we can't possible get it right without seeing it in action with hundreds of people on. That said, we can definitely start to tweak some numbers to reduce hiccups.

**Comment by Dakyo** [comment]
Understood, sorry if I was a bit abrasive with the title. It's good to see (at least 1) dev actually cares about the reports.
