### ISSUE TITLE
Loque'nahak's respawn timer is too short.

### ISSUE THREAD

**Issue by corcaroli** [FeenixServerProject/Wrath_3.3.5_Issue_tracker#165]
[Loque'nahak](http://wowwiki.wikia.com/wiki/Loque%27nahak), a rare NPC that can be found in Sholazar Basin, has a too short respawn timer. Here is the evidence:
1. As you can see on the following screenshot, I killed Loque'nahak at 1:09 AM server time.
![](http://i.imgur.com/4n2r0wz.jpg)
2. At 1:28 AM server time(in 19 minutes after that first kill) I found (and killed too, just didn't screenshot that) Loque'nahak on the same spot.
![](http://i.imgur.com/7bLHg27.jpg)
3. And 2:01 AM server time(33 minutes after the second kill) I found him again, in a different location this time.
![](http://i.imgur.com/hyulwXb.jpg)

So apparently its respawn timer is less than 19 minutes, while it is obviously supposed to be several hours (since it's a rare NPC). 

P.S. I can't really tell much about other rare NPCs' respawn timers since i haven't been encountering them this frequently. (This probably means they're fine, but you never know...)

**Comment by lajhar** [comment]
Fixed.
Fix confirmed.
Liva as 2.9a
