### ISSUE TITLE
Eck the Ferotious (Gundrak)

### ISSUE THREAD

**Issue by fyrinx** [FeenixServerProject/Wrath_3.3.5_Issue_tracker#17]
As I were testing out Gundrak, I stumbled across the boss Eck the Ferotious. I fought it, but died from an instakill later on the fight (34k hit). 

An other thing that were noted, was that **the boss shouldn't even be avalible in normal mode.** 

Here is a video footage of it. 

https://vimeo.com/200476292

And here is recount damage from damage taken right before death. 

http://imgur.com/a/sSR2Q

**Comment by deathstreal** [comment]
Eck the Ferocious enrages 60-90s into the fight, increasing his Attack Speed by 150% and all Damage by 500%. 
http://wowwiki.wikia.com/wiki/Eck_the_Ferocious

**Comment by fyrinx** [comment]
Ah damn. Should have read that. Might have survived those hits if I used frost presence.

**Comment by fyrinx** [comment]
Anyway that boss shouldnt be there in normal mode.
