### ISSUE TITLE
[Important] Before Releasing 3.1 Thursday

### ISSUE THREAD

**Issue by Bellzubab** [FeenixServerProject/Wrath_3.3.5_Issue_tracker#173]
Please, please, **PLEASE** quadruple-check the loot table of Emalon (both 10 and 25) before adding him to VoA. Since S5 is being extended, Emalon should not drop any Furious Gladiator's items.

I can't overstate how important this is. I understand this is probably on a to-do list somewhere, but would like to make sure it isn't overlooked.

We really don't need people running around with 232 PvP gear that should be inaccessible (like they already are with some WG stuff that should have been as well).

Thank you for looking into this.

**Comment by Zerixx** [comment]
We got it ^^ - Thanks for the report.

**Comment by Bellzubab** [comment]
Aaaaand you totally butched this. Great job.

**Comment by Dakyo** [comment]
Much furious gear from voa, much wow ))
