### ISSUE TITLE
Ulduar 25 Dropping Emblems of Valor

### ISSUE THREAD

**Issue by dangreenberggit** [FeenixServerProject/Wrath_3.3.5_Issue_tracker#175]
Bosses in Ulduar 25 should drop Emblems of Conquest.

**Comment by corcaroli** [comment]
Yeah, and some of 10 man mode bosses drop Emblems of Conquest.

**Comment by corcaroli** [comment]
Actually, these problems are listed [here](https://github.com/FeenixServerProject/Wrath_3.3.5_Issue_tracker/issues/163) already.

**Comment by Zerixx** [comment]
Closing. All issues in one thread.
