### ISSUE TITLE
Deadly Gladiator's gear from Conquest Vendor

### ISSUE THREAD

**Issue by Bellzubab** [FeenixServerProject/Wrath_3.3.5_Issue_tracker#176]
This is S5. You should NOT be able to buy the current season's Arena gear for Emblems.

When S6 starts, then this could be re-implemented.

**Comment by Bellzubab** [comment]
This is a (poorly written) query that will show you which entries need to be removed, assuming you have the same table setup as stock trinity...

SELECT world.npc_vendor.entry, world.npc_vendor.item, world.item_template.name
FROM world.npc_vendor
INNER JOIN world.item_template ON world.npc_vendor.item=world.item_template.entry
WHERE world.npc_vendor.entry = '33963' AND world.item_template.name LIKE 'deadly gladiator%' OR world.npc_vendor.entry = '33964' AND world.item_template.name LIKE 'deadly gladiator%';

**Comment by lajhar** [comment]
Fixed.
Fix confirmed on PTR
