### ISSUE TITLE
Ulduar 10 Man - Iron Council HM - Steelbreaker heals to full HP randomly and kills everyone

### ISSUE THREAD

**Issue by nfernix** [FeenixServerProject/Wrath_3.3.5_Issue_tracker#177]
https://clips.twitch.tv/OriginalMoralPlumberWTRuck

Not sure what caused it. We got him to 10-15% HP and the boss jumped to full HP and started one shotting people.

We were trying to figure out what was causing it, and our best guess is that once the enrage timer said 10 minutes exactly that's when it happened. So maybe something is coded wrong in the server.

**Comment by corcaroli** [comment]
Well, one can see from your video that he got 8 additional Electrical Charges, which healed him to full and increased his damage by 200%. The question is why he got them all of a sudden without people dying in that moment.
~~Yeah, sorry for a useless comment :-D~~

**Comment by nfernix** [comment]
It's whenever he kills a pet or totem.

We finally killed it, we had the shamans get rid of totems and dismiss all pets. Was a DPS loss, but we were fine.

**Comment by HelloKitty** [comment]
@Zerixx Steelbreaker's KilledUnit should check if the unit was a player

```
            void KilledUnit(Unit* who) override
            {
                if (who->GetTypeId() == TYPEID_PLAYER)
                    Talk(SAY_STEELBREAKER_SLAY);

                if (phase == 3)
                    DoCast(me, SPELL_ELECTRICAL_CHARGE);
            }
```

Should be

```
            void KilledUnit(Unit* who) override
            {
                if (who->GetTypeId() == TYPEID_PLAYER)
                    Talk(SAY_STEELBREAKER_SLAY);

                if (phase == 3 && who->GetGUID().IsPlayer())
                    DoCast(me, SPELL_ELECTRICAL_CHARGE);
            }
```

Otherwise he's going to gain ID - 61902 Electrical Charge stacks from everything and make the encounter very RNG and comp dependent.

**Comment by Zerixx** [comment]
@HelloKitty  this was fixed in one of my recent commits. Plans to go live soon.

**Comment by Zerixx** [comment]
Fixed 3/29/17 - Closing
