### ISSUE TITLE
Salvaging Ulduar bosses

### ISSUE THREAD

**Issue by BoberinoRosserino** [FeenixServerProject/Wrath_3.3.5_Issue_tracker#178]
As title states, yesterday I couldn't salvage both Flame Leviathan and XT-002 Deconstructor in Ulduar 25 man. The loot window with salvaged parts just pops up for a second and then immediately closes rendering boss non-interactable. I tried salavging Flame Leviathan with auto loot enabled and XT with shift-click(no auto loot), yet same results.

**Comment by corcaroli** [comment]
This is because of the master loot. Ask your raid leader to switch to  group loot or free for all after the loot was distributed.

**Comment by BoberinoRosserino** [comment]
Thanks for the answer, but again, is that the expected behavior? I don't remember any problems salvaging them on retail, but it was long time ago so my memory could fail me.

**Comment by Bellzubab** [comment]
I salvaged Flame Leviathan (10 mode) yesterday, and there weren't any items. He then despawned a few seconds later. It worked fine the other 2 times I've done it, so no idea if it was just some kind of freak bug.

Was Group Loot every time.
