### ISSUE TITLE
Auction House - Bid not refunding after self-outbid

### ISSUE THREAD

**Issue by ukidono** [FeenixServerProject/Wrath_3.3.5_Issue_tracker#182]
I've experienced this bug not too long ago.
I bid on the item below for 71g, and than decided not to wait and bought it thinking the bid money should return back to me. Which seems to be bugged, i haven't got a notification that i was outbid and haven't received the bid money back either. 

The bug looks like since it was me outbidding myself, it doesn't register the refund method.
![image](https://cloud.githubusercontent.com/assets/5203307/24070811/54526160-0bd5-11e7-9cb0-801a987444c7.png)

**Comment by Bellzubab** [comment]
Tried to replicate, but it was working as intended for me.

**Comment by ukidono** [comment]
@Bellzubab can you take a video of it working?

Here is your video proof of the so called bug.

https://www.youtube.com/watch?v=SNEKRU7pJYw

**Comment by Bellzubab** [comment]
@ukidono Look at your actual gold total.

When you bid on it, you lose 3g88s59c.

When you buy it out, you only lost the difference between the bid and buy out amounts.

You started with 20366g24s85c (good lord, share the wealth pls)

You bid 3g88s59c, now your total is 20362g36s26c.

You buyout the item (at the cost of 4g99s61c), and your gold goes to 20361g25s24c. Meaning that only charged you 1g11s02c.

That number is the exact difference between your bid 3g88s59c and your buyout 4g99s61c. You didn't actually lose any money.
