### ISSUE TITLE
Tier 7 raid instances and heroic 5 man dungeons grant wrong type of Emblems

### ISSUE THREAD

**Issue by corcaroli** [FeenixServerProject/Wrath_3.3.5_Issue_tracker#185]
You've changed the type of emblems dropped by mentioned raids/dungeons to Conquest(25 man) and Valor(10 man and heroic 5 man dungeons) with the Ulduar release. However, the type of Emblems dropped was changed only in the [patch 3.2.0](http://wowwiki.wikia.com/wiki/Patch_3.2.0#Dungeons_and_Raids):

> Any dungeons that previously dropped [Emblems of Heroism] or [Valor], such as Naxxramas or Heroic Halls of Stone, will now drop [Emblems of Conquest] instead. Emblems of Conquest can still be converted to Valor or Heroism. 

I don't know if this change was intentional, so I'm reporting this just in case.

**Comment by Zerixx** [comment]
Known. Organizing a fix for it ^^
