### ISSUE TITLE
Titan-forged waistguard not possible to purchase

### ISSUE THREAD

**Issue by cudd** [FeenixServerProject/Wrath_3.3.5_Issue_tracker#186]
Hi.

I can purchase Titan-forged waistguard on my priest but not shaman (i'ts not in the shop). I've tryed clearing cache etc. Was told in a ticket to report it here.

Kinds regards

**Comment by Bellzubab** [comment]
#174 

There are a lot of issues with the WG vendors. The staff need to decide if they want the 213 stuff implemented or not, and definitely implement all the 200 stuff.

**Comment by lajhar** [comment]
Fixed, closing this issue, see #174 for details
