### ISSUE TITLE
Detonating Lasher, Freya (Ulduar) adds keeps detonating while alive

### ISSUE THREAD

**Issue by fyrinx** [FeenixServerProject/Wrath_3.3.5_Issue_tracker#187]
My apologies for lack of formality here.

The adds from Freya detonates while alive. Should only be happening when they die.

**Comment by HelloKitty** [comment]
@fyrinx Are you sure it's not ID - 62608 Flame Lash?

**Comment by lajhar** [comment]
Fix confirmed on PTR
