### ISSUE TITLE
They hate me ! The oracle daylies and NPC are buggy (for me)

### ISSUE THREAD

**Issue by Remag123** [FeenixServerProject/Wrath_3.3.5_Issue_tracker#192]
I finished the Prequest for the oracles in the Sholazzar Basin and have now finished my first 3 Daylis.
But I can not finish them at the Oracle NPC. The NPC are''green'' for me, have a question mark over his head und do not attack me, but I can no longer access it. Instead, I can attack them but.
I have already deleted the WDB, WTF folder and all addons. Also the Lich Mob in the cave in the Sholazzarbecken you have to kill at the end of the Oracles Pre Quest series I killed again. Everything without success.

**Comment by corcaroli** [comment]
Have you tried going to the Reputation tab of your character panel and look if the "at war" checkbox at the Oracles reputation is checked? If it is, just uncheck it.

**Comment by Remag123** [comment]
yeah. thats it ! i´m a noob. sorry :D thank you very much !
