### ISSUE TITLE
Quest - [80] Free Your Mind

### ISSUE THREAD

**Issue by everywith1** [FeenixServerProject/Wrath_3.3.5_Issue_tracker#195]
http://www.wowhead.com/quest=12893/free-your-mind

In this quest you're supposed to kill the three mobs, however when you get them down to about 100 HP, they run back to their original position, and then despawn.

Quest is uncompleted because you haven't killed the three mobs and then used the device on their corpse.

**Comment by corcaroli** [comment]
[That's a duplicate.](https://github.com/FeenixServerProject/Wrath_3.3.5_Issue_tracker/issues/138)

**Comment by everywith1** [comment]
I see it now, i tried searching and got no results, so i posted a new one.
