### ISSUE TITLE
[3.3.5] Scripts/Spell Thorim's 10man Spells

### ISSUE THREAD

**Issue by HelloKitty** [FeenixServerProject/Wrath_3.3.5_Issue_tracker#196]
**Description:**

Thorim and Sif are casting the wrong spells on 10man mode. Makes it very hard to kill. Probably easier to kill 25man Thorim Hardmode at the moment.

**Current behaviour:**

Sif is casting 25man Spell ID [Frostbolt Volley 62604](http://www.wowhead.com/spell=62604).
Sif is casting 25man Spell ID [Frostbolt 62601](http://www.wowhead.com/spell=62601).
Sif is casting 25man Spell ID [Blizzard 62602](http://www.wowhead.com/spell=62602)

Thorim is casting 25man Spell ID [Chain Lightning 62131](http://www.wowhead.com/spell=62131)

**Expected behaviour:**

Sif should be casting [Frostbolt Volley 62580](http://www.wowhead.com/spell=62580)
Sif should be casting [Frostbolt 62583](http://www.wowhead.com/spell=62583)
Sif should be casting [Blizzard 62576](http://www.wowhead.com/spell=62576)

Thorim should be casting [Chain Lightning 64390](http://www.wowhead.com/spell=64390)

**Proof:**

Our log: http://www.worldoflogs.com/reports/rt-2cizyqix5mwdzdb6/deaths/?s=15888&e=16002

**Solution:**

If Sif is smart_scripts then maybe you can use SMART_EVENT_FLAG_DIFFICULTY_3 and SMART_EVENT_FLAG_DIFFICULTY_2? I could be wrong. Don't know what flags are used in 10 vs 25 in instances that only have 10 and 25 not normal vs heroic. May have to move her into a script itself to using Is25ManRaid with differing IDs. I don't know if Trinitycore 3.3.5 provides a way to deal with 10 vs 25 spell differences with smart scripts or in a better way then explicitly checking raid-size in the creature script.

For Thormin, same solution as Sif minus the part about smart scripts. ScriptedAI::Is25ManRaid

**Comment by deathstreal** [comment]
Nice find.

**Comment by lajhar** [comment]
Not a DB issue, the spells are being defined wrongly in the core.

> SPELL_BLIZZARD_10 = 62577,
> SPELL_BLIZZARD_25 = 62603,

Need to be swapped, also

> SPELL_CHAIN_LIGHTNING_10 = 62131,
> SPELL_CHAIN_LIGHTNING_25 = 64390,

Need to be swapped aswell.

However, Frostbolt and Frostbolt Valley have only one difficulty of spell being defined currently.

**Comment by HelloKitty** [comment]
Oh, well if they're defined in the script then that's a rather simple fix. Very good news!

**Comment by Zerixx** [comment]
Good find, guys.

Off topic: @HelloKitty Fan of your work. :)

**Comment by HelloKitty** [comment]
@Zerixx =o you mean Freecraft Core? I appreciate it. I'm a fan of the server!

**Comment by Zerixx** [comment]
@HelloKitty YES! It's great stuff, and I appreciate it ^^

**Comment by kingbroos** [comment]
I have a fix ready for this

@HelloKitty Where did you get the info about the spell ID's? It seems like wowwiki doesn't mention this

**Comment by Tapswhenoom** [comment]
I have a fix ready for this

@HelloKitty Where did you get the info about the spell ID's? It seems like wowwiki doesn't mention this

**Comment by HelloKitty** [comment]
@Fapswhenoom I just checked http://www.wowhead.com/npc=33196/sif which lists her 10 and 25 man spell ids.

Here for Thorim http://www.wowhead.com/npc=32865/thorim
