### ISSUE TITLE
[3.3.5] Scripts Thorim Lightning Charge

### ISSUE THREAD

**Issue by HelloKitty** [FeenixServerProject/Wrath_3.3.5_Issue_tracker#197]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

**Description:**

Thorim's [Lightning Charge](http://www.wowhead.com/spell=62279/lightning-charge) is not functioning properly.

**Current behaviour:**

His charge is not always resetting after p2 wipes causing stacks to be generated during the gauntlet. He'll cast the spell that starts generating charges as he resets causing the bug sometimes.

**Expected behaviour:**

He should have no lightning charge stacks when the encounter resets or starts. Stacks should not be generated during the gauntlet event.

**Steps to reproduce the problem:**

1. Pull Thorim
2. Complete Gauntlet
3. Die in p2 (may have to have MC creature up too)

**Comment by Tapswhenoom** [comment]
IIRC this doesn't happen on 25M. I'll try it out tonight and see if I can reproduce this

**Comment by HelloKitty** [comment]
@Fapswhenoom It didn't happen always but we noticed it would happen if we wiped during the second phase. Maybe try wiping shortly before he's going to gain a charge? Not really sure what was causing it. We couldn't repro it consistently and of course I can't exactly work on reproducing it myself since stock TC has no Thorim.

**Comment by deathstreal** [comment]
I can confirm it happens on 25M.
