### ISSUE TITLE
Frenzyheart and Oracles reputation chain quest

### ISSUE THREAD

**Issue by hairychestfan** [FeenixServerProject/Wrath_3.3.5_Issue_tracker#198]
So in order to start the quest chain for Frenzyheart Tribe/Oracles you need to kill a mob called Pitch in sholazar basin. after killing it, the npc next to it should get quest sign over his head with whom you start the quest chain. but nothing happens. i cleared my folders. please fix this. thank you
https://www.youtube.com/watch?v=Vwbp8v7qGvA

**Comment by lajhar** [comment]
Hey!
You need to be on quest "Part-time hunter" (or need to have this quest done, as in the video you've linked) in order to be able to pick up the quest you are talking about.
Tested, and works as intended
