### ISSUE TITLE
Mimiron laser barrage in p4

### ISSUE THREAD

**Issue by tonystark9911** [FeenixServerProject/Wrath_3.3.5_Issue_tracker#209]
laser barrages in p4 are completely fucked up and dont match the visual, making it insanely annoying to deal with this phase

**Comment by HelloKitty** [comment]
On TC this spell seems functional. So, unless Feenix changed something I'd imagine this is an issue with tracking the target or facing.

**Comment by tonystark9911** [comment]
I'd also like to know why these "fixes" get into the live server without being properly tested or atleast being able to fix the problem fast, this made the boss impossible for some groups and a pain in the ass for the others because they have to spend countless wipes figuring out where the hell he actually throws the barrage.

**Comment by lajhar** [comment]
I can assure you that we test every single fix before we push them to live.
However, such side-effects, where visual effects are not necessarily following the spell sometimes hard to be encountered without having multiple players in the party/raid.
I went there, triggered phase 4, saw the spell being casted, and saw the damage on myself. I had no reason to doubt. 

Fix was reverted meanwhile, /close
