### ISSUE TITLE
[Quest]Sarathstra, Scourge of the North

### ISSUE THREAD

**Issue by fyrinx** [FeenixServerProject/Wrath_3.3.5_Issue_tracker#21]
The quest requires you to kill Sarathstra. Problem is with it is that Sarastra seem to attack just above you and you can't use melee abilities against the npc. I have tried moving around, but the mob simply won't get down on my level. 

The quest: [Sarathstra, Scourge of the North](http://www.wowhead.com/quest=12097/sarathstra-scourge-of-the-north) 

A screenie:
http://imgur.com/a/91luE

In addition. This quest requires you to have done [To Dragon's Fall](http://www.wowhead.com/quest=12095/to-dragons-fall). Which is supposed to be avalible after doing the following quests:

[Wanted: Dreadtalon](http://www.wowhead.com/quest=12091/wanted-dreadtalon)
[Wanted: Gigantaur](http://www.wowhead.com/quest=12090/wanted-gigantaur)
[Wanted: Magister Keldonus](http://www.wowhead.com/quest=12089/wanted-magister-keldonus)

That was not the case. ;)

**Comment by Zerixx** [comment]
Fix on PreLive
