### ISSUE TITLE
Ghostpaw Runner Flees

### ISSUE THREAD

**Issue by dangreenberggit** [FeenixServerProject/Wrath_3.3.5_Issue_tracker#22]
Current: Ghostpaw Runner (3823) flees at low HP
Desired: the wolf takes it like a man

**Comment by devastator** [comment]
http://www.wowhead.com/npc=3823/ghostpaw-runner#comments:id=176948
By Nerizor (18,001 – 3·28·133) on 2007/10/31 (Patch 2.2.3)		
These guys sure are runners - they're one of the few animals that actually run away in fear!
