### ISSUE TITLE
Unable to move after releasing spirit

### ISSUE THREAD

**Issue by hairychestfan** [FeenixServerProject/Wrath_3.3.5_Issue_tracker#223]
Uppon death when you click release spirit button you are stuck as ghost and are unable to move untill you relog. this annoying bug needs to be fixed asap!! also happens sometimes when you charge something you get stuck in place. its time to fix this

**Comment by lajhar** [comment]
I can't reproduce the spirit stuck issue, the charge is probably AC related.
Need additional details or reproduction guide
