### ISSUE TITLE
Some Make Lemonade, Some Make Liquor

### ISSUE THREAD

**Issue by hairychestfan** [FeenixServerProject/Wrath_3.3.5_Issue_tracker#225]
this quest is bugged. there is no levers to pull to drop the fruits from the trees. there was only 1 lever and it dropped Papaya. other ropes missing making the quest unable to complete. its an essential quest for cooking leveling..  https://www.youtube.com/watch?v=x7l67GlavIs

**Comment by lajhar** [comment]
#10
