### ISSUE TITLE
Icecrown quest [Free Your Mind] broken

### ISSUE THREAD

**Issue by gianclaudio-giordano** [FeenixServerProject/Wrath_3.3.5_Issue_tracker#230]
The quest (http://www.wowhead.com/quest=12893/free-your-mind) obteinable in Icecrown at The Shadow Vault (tested on alliance, can't say if it's the same on horde) can not be completed because the involved NPCs whose corpses need to be interacted with have an instant respawn, and do not drop a corpse at all. Video proof of me trying to do it:
https://www.youtube.com/watch?v=enUhL_N95Vc
One of the three NPCs involved is shown to instantly revive when killed, leaving no corpses on the floor, therefore making the quest item unuseable. Same for Lady Nightswood NPC

**Comment by lajhar** [comment]
#138
