### ISSUE TITLE
Upgarde Keep Dragonflayer Strategist has crazy toys

### ISSUE THREAD

**Issue by dangreenberggit** [FeenixServerProject/Wrath_3.3.5_Issue_tracker#26]
Dragonflayer Strategist (23956) sets time bombs (either spell 60227 summoning 32246 or 54962 summoning 29684) that move. Also, it looked like this dude was throwing those blue checkerboard-pattern boxes.

**Comment by Qingle** [comment]
As I understand it, SPELL60227 Wild summons NPC32246. NPC32246 then uses SPELL59686 for the targeting/damage. It then force despawns NPC32246 on execution.

That's how I think it works at least :smile:

**Comment by lajhar** [comment]
Bombs no longer move on PreLive
