### ISSUE TITLE
Talent: Improved Earth Shield broken

### ISSUE THREAD

**Issue by pucko91** [FeenixServerProject/Wrath_3.3.5_Issue_tracker#29]
Realm of Shadows 3.3.5 Error Report Form

Report ID: Titum005? maybe 006 nvm

Reporter Name: Titum

Date/Time: 17012717:35ST

Error Severity: big

Zone/Instance: --

What type of error occurred?: The talent Improved Earth Shield does not give Earth Shield 2 extra charges but remains at 8, haven't concluded if the extra healing the talent give is broken aswell

What was the actual result vs. the expected result?: Acctual result is 8 charges of Earth Shield, exspected 10.

Can the error be repeated? If so, what are the steps?: Make Shammy, specc it.

Link to Video Evidence: easily repeatable so not required imo

External/Related Links: http://wowwiki.wikia.com/wiki/Improved_Earth_Shield

Please detail your character’s race, class, and items (optional): Orc Shaman.

**Comment by pucko91** [comment]
UPDATE!
The talent works fine, it's Earthshield that starts off with 6 charges (like in tbc) and goes to 8 with the talent where is should have 8 as baseline and go to 10.

**Comment by Zerixx** [comment]
Should we close?

**Comment by pucko91** [comment]
If you wish, I can make a new one with the correct facts.

**Comment by Zerixx** [comment]
Please do!
