### ISSUE TITLE
Spell: Reincarnation doesn't consume an ankh even without the glpyh.

### ISSUE THREAD

**Issue by pucko91** [FeenixServerProject/Wrath_3.3.5_Issue_tracker#35]
Realm of Shadows 3.3.5 Error Report Form

Report ID: Titum008

Reporter Name: Titum

Date/Time: 170128 12:59ST

Error Severity: big

Zone/Instance: --

What type of error occurred?: The Spell Reincarnation (spell id = 20608) doesn't consume an ankh (item id = 17030) when used. Now there is a glyph that also remove the need for an ankh to use the ability but without the glyph you just need an ankh in your bag to use reincarnation and no nakh is consumed. Glyph of renewed life (item id=43385)

What was the actual result vs. the expected result?: Actual result is you have the same amounts of ankh in your bags after using spell reincarnation (1 should have been consumed).

Can the error be repeated? If so, what are the steps?: Make Shammy, die.

Link to Video Evidence: easily repeatable so not required imo

External/Related Links:http://wowwiki.wikia.com/wiki/Glyph_of_Renewed_Life

Please detail your character’s race, class, and items (optional): Orc Shaman.

**Comment by lajhar** [comment]
Issue confirmed.

Nothing much to add here, Reincarnation (20608) simply doesn't consume its reagent (Ankh - 17030).
Might be related to its minor glyph, which allows you to reincarnate without having reagent.

**Comment by Zerixx** [comment]
Fixed. Will be on prelive soon.

**Comment by corcaroli** [comment]
This still doesn't work.
