### ISSUE TITLE
"Aura of Lost Hope" is plaguing players in Old Kingdom dungeon

### ISSUE THREAD

**Issue by dangreenberggit** [FeenixServerProject/Wrath_3.3.5_Issue_tracker#37]
Current: Aura of Lost Hope (56709) is making people rage in Ahn'Kahet: The Old Kingdom, and rage hard. People are getting it, it is spontaneously stacking, it is putting people in combat, etc.

Desired: It seems aura should only apply when next to Plague Walkers (56709 and 31466), and should only stack when players afflicted by it are near each other.

**Comment by Zerixx** [comment]
Fix on PreLive.
