### ISSUE TITLE
Alliance - Druid class quest(Bear Form quest) : Bug

### ISSUE THREAD

**Issue by kjraider** [FeenixServerProject/Wrath_3.3.5_Issue_tracker#39]
Quest:Body and Heart (Alliance)

When you go to the moonkin cave in darkshore (coordinates [43, 45]) yoU should see a stone to use the quest item [Cenarion Lunardust](Provided) to spawn Lunaclaw to complete the quest. Currently the stone is not there and I cannot get bear from(kind of important when you are leveling a guild tank). 

http://wowwiki.wikia.com/wiki/Quest:Body_and_Heart_(Alliance)
http://www.wowhead.com/quest=6001/body-and-heart#screenshots:id=69901

![25979-body-and-heart-moonkin-cave-this-is-where-moonkin-stone-is](https://cloud.githubusercontent.com/assets/20013784/22495474/d25444ba-e80e-11e6-9aea-612777c0a937.jpg)

![69901](https://cloud.githubusercontent.com/assets/20013784/22495471/c51172d2-e80e-11e6-80aa-c9b219c6a37e.jpg)

**Comment by FRBooo** [comment]
I did this quest 3 days ago, it worked. Only thing was that i did not have to summon the bear, the owlkin that spawns after killing the bear was already there, if not permanent, it at least worked for completion
