### ISSUE TITLE
Sartharion (10/25) - Vesperon - Twilight Torment - 1 Shotting raid members

### ISSUE THREAD

**Issue by nfernix** [FeenixServerProject/Wrath_3.3.5_Issue_tracker#41]
I cannot confirm that this bug exist in the 25 man version as my guild has only attempted the 10 man version. When Vesperon lands and the portal spawns the add inside is casting Twilight Torment and instantly killing any raid member, including the tank. This happened during the Sarth +2 Drakes attempts and when we decided to just kill Vesperon by himself.

Vesperon's disciple will place Twilight Torment (http://www.wowhead.com/?spell=58835) on the raid frequently, which increases fire and shadow damage taken by 75% and causes you to deal damage to yourself on hit. It used to be possible to temporarily remove the Twilight Torment debuff with any damage other than autoattacking, but the ability was changed with patch 3.0.8 and this is not possible anymore. This disciple can be ignored if fighting Vesperon alone, but is extremely dangerous in a multi-drake Sartharion fight.

**Comment by papoolee** [comment]
The whole mechanic of the fight is that if the tank wants to survive the breath from Vesperon, you've gotta pop defensive cooldowns to be able to withstand it, otherwise you get one shot. It happens once when he lands and every 17 seconds from that point i think. 

Defensive cooldowns are cooldowns like "Pain Suppression" for example.

**Comment by nfernix** [comment]
papoolee, that's not what is causing the 1 shot. You need to read the post before you just randomly type something in return.

The ability is called Twilight Torment, it comes from the add inside the portal. It's targeting random party members and instantly killing them, including tanks.

**Comment by Zerixx** [comment]
This is normal behavior. Here's why I say this:

In **most** cases Vesperon is the third and last drake you add to the mixer when you're doing Sarth. When you do have Vesperon, he dies before portal is spawned or it's generally considered a wipe. This is the sole reason for that.. If you're doing +1, or +2 I recommend Tenebron first and then add Shadron. Only when your DPS/Tanks can handle the load will you be able to include Vesperon. He makes the fight difficult. +2 -> +3 is a MASSIVE difficulty increase.
