### ISSUE TITLE
Sons of Hodir Quests from Objects Disabled?

### ISSUE THREAD

**Issue by dangreenberggit** [FeenixServerProject/Wrath_3.3.5_Issue_tracker#43]
Many quests that require starting or turning in quests at objects for the Sons of Hodir cannot be started or turned in. Exclamation points do not appear, and if the quest is completed, question marks cannot appear.
I'm not sure what the extent of this issue is--if this is related to objects, Sons of Hodir, or what, but they're all broken (other questgivers in the zone do seem to work). Mouse-overs on the objects simply show gears.

**Comment by Zerixx** [comment]
Fixed: 02/02/17
