### ISSUE TITLE
Wintergrasp vendor wrong/missing items

### ISSUE THREAD

**Issue by madsoigard** [FeenixServerProject/Wrath_3.3.5_Issue_tracker#44]
Not sure if this is supposed to be 3.0.8 or 3.1.0 or something later, but I noticed that no haste items are sold. There is a list of items sold by the vendor on wowwiki, and the patch they were added when you click the items.

Here is the link for the horde vendor:
http://wowwiki.wikia.com/wiki/Stone_Guard_Mukar

Here are links for some haste items added in 3.0.8:
http://wowwiki.wikia.com/wiki/Titan-Forged_Hood_of_Salvation
http://wowwiki.wikia.com/wiki/Titan-Forged_Slippers_of_Salvation

Much more added in 3.1.0.

**Comment by Zerixx** [comment]
Basically, we have a way to switch patches by a config value. These will be added when the next patch comes by default :)

**Comment by madsoigard** [comment]
But you only removed the 213 items, while not putting 200 items back in? There are supposed to be more items this patch.

**Comment by madsoigard** [comment]
This is 3.0.8 right? Or am I mistaken

**Comment by Zerixx** [comment]
Technically, we're on 3.0.3.

**Comment by Zerixx** [comment]
However, if you think those should be added (since we'll only skip straight to 3.1 not 3.0.8) we might be able to arrange that.

**Comment by madsoigard** [comment]
Ah, cool!

**Comment by madsoigard** [comment]
I have the on-use 213 haste trinket equipped, I can delete it if the marks are refunded as I would rather have the head/boots anyway =)

**Comment by madsoigard** [comment]
Will this be happening? If not, when is the 3.1.0 patch releasing?
