### ISSUE TITLE
Buffing someone in combat does not get the buffer in combat

### ISSUE THREAD

**Issue by madsoigard** [FeenixServerProject/Wrath_3.3.5_Issue_tracker#45]
Noticed while playing arena. Rogues sapping my partner even though I'm in combat and being buffed by him. This is a crucial issue in itself, but if it works like this with healing aswell, it is gamebreaking.

**Comment by lajhar** [comment]
Cannot reproduce.
My toons entering to combat properly while buffing/healing a friendly target being in combat.
Need video or detailed reproduction guide.
