### ISSUE TITLE
"/who" Function does not work. (NVM IM STUPID)

### ISSUE THREAD

**Issue by papoolee** [FeenixServerProject/Wrath_3.3.5_Issue_tracker#53]
RoS 3.3.5a Error Report Form

Reporter Name: Papoolee

Date/Time: 2/5/2017

Error Severity: Medium

Zone/Instance: Anywhere

What type of error occurred?: Does not show the relevant information.

What was the actual result vs. the expected result?: 
Doesn't show any results vs should show the people inside the zone.

Can the error be repeated? If so, what are the steps?: Yes, just be in any zone and try /who dalaran or /who stormpeaks or anything.

Link to Video Evidence: Not needed

External/Related Links: not needed

Please detail your character’s race, class, and items (optional): Kappa Priest

**Comment by corcaroli** [comment]
That's not how it works here. To check a particular zone you should type /who z-"zoneName", i.e. /who z-"dalaran" or /who z-"storm peaks".

**Comment by papoolee** [comment]
Oh wow i love you, thank you. I should have done my research before posting this, my apologies.

**Comment by Zerixx** [comment]
Thanks anyways Pap.
