### ISSUE TITLE
[Event] DMF event not up. [FIXED]

### ISSUE THREAD

**Issue by papoolee** [FeenixServerProject/Wrath_3.3.5_Issue_tracker#54]
RoS 3.3.5a Error Report Form

Reporter Name: Papoolee

Date/Time: 2/5/2017

Error Severity: High

Zone/Instance: Anywhere

What type of error occurred?: Does not spawn the event.

What was the actual result vs. the expected result?:
DMF Should be up first Sunday after the first Saturday of the month, should be @ 03:00 ST.

Can the error be repeated? If so, what are the steps?: Go look for it!

Link to Video Evidence: Not needed

External/Related Links: http://wow.gamepedia.com/Darkmoon_Faire

Please detail your character’s race, class, and items (optional): Kappa Priest

**Comment by dangreenberggit** [comment]
Some additional information and minor corrections for this patch, as OP link is from later patches:

From [WoW Wiki](http://wowwiki.wikia.com/wiki/Darkmoon_Faire_(old)): 
> "The Darkmoon Faire visits once a month, starting at 00:01 on the Sunday before the 1st Monday of each month. The event dates are automatically added to the in-game calendar."

Issues:
- The 1st Monday of the month is the 6th of February, so the Darkmoon Faire should have been up at 00:01 on Sunday, February 5th. (It is currently 10:00 Feb 6th, no Kappa).
- The DMF NPC in Orgrimmar (14843) states that the DMF should be in Mulgore--if that is not the case, this is, of course, incorrect 
- DMF isn't in the in-game calendar

**Comment by Zerixx** [comment]
Time tables changed in DB. Restart of server should fix.
