### ISSUE TITLE
Northrend fishing daily quests seem to be broken

### ISSUE THREAD

**Issue by corcaroli** [FeenixServerProject/Wrath_3.3.5_Issue_tracker#55]
Currently, it doesn't seem possible to complete following Marcia Chase's fishing daily quests: 
- Dangerously Delicious 
- Disarmed! 
- Blood Is Thicker. 

The reason for that is that the quest items required for that, that is:
- Terrorfish from Wintergrasp waters 
- Severed Arm from the water outside the Violet Hold 
- Bloodtooth Frenzy from Pools of Blood in Borean Tundra 

cannot be fished (at least it appears to be so) - players get the usual location's fishing loot instead. (I could not fish any quest items after 20+ successfull attempts, and a fellow fisherman said he tried ~50 times and still could not get them)
I have a strong suspicion that this issue applies to the other two Marcia's quest, although that's but an assumption.
A possible reason for that could be the absence of the required items in the database. :^)
Hoping for a quick fix for game's fun sake.

**Comment by Zerixx** [comment]
When was this added to the game? What patch.

**Comment by tomtoes** [comment]
Seems to be patch 3.1.0
[http://wowwiki.wikia.com/wiki/Bag_of_Fishing_Treasures_(Dalaran)](url)

**Comment by Zerixx** [comment]
Well, when we hit patch 3.1 (coming with Ulduar release, technically), we'll see this again.
