### ISSUE TITLE
Fishing Dailies bugged

### ISSUE THREAD

**Issue by Forcefromsunwell** [FeenixServerProject/Wrath_3.3.5_Issue_tracker#58]
Yeasterday i tried to do the Borean Tundra "Blood is Thicker" quest and didnt work.
Today it is "Jewel of the sewers" and been fishing for 45min and it doesn't drop.

**Comment by papoolee** [comment]
This is making me cry, tried 3 different fishing dailies and none worked (OP's ones + "Dangerously Delicious").

**Comment by corcaroli** [comment]
Apparently Northrend fishing dailies won't be available till Ulduar release. I had made a post(check #55) about this issue ealier, and that's what i was told.

**Comment by Forcefromsunwell** [comment]
It's very strange that the GM's didn't say anything regarding this to me since i have up 2 tickets regarding the fishing dailys. 

There is no reason for fishing dailys coming whe ulduar does? They are suppose to be there "unlocked" just as the cooking dailys, JC dailys etc.

**Comment by Zerixx** [comment]
@Forcefromsunwell Hey, man. I had to be out yesterday -- sorry for no response on this. @corcaroli  is correct, this bit won't come until our equivalent of 3.1 (Ulduar).
