### ISSUE TITLE
[Jewelcrafting] Titanium ore prospecting

### ISSUE THREAD

**Issue by niggerious** [FeenixServerProject/Wrath_3.3.5_Issue_tracker#59]
Prospecting from titanium ore does not give titanium powders at all.
Tried like 10 times prospecting titanium ores, but no powders.

I talked with one player who got 450 JC too, and he said his first prospecting from titanium ore gave him 1 powder, then he waited some day, and never get any other titanium powder at all.

my addon says it's drop rate is 65%
in wowhead it says 57% ( i think that's just not even the 3.3.5 or wotlk patches anymore)
others say in wowhead:

By trulez (303 – 3) on 2009/06/28 (Patch 3.1.3)		
This can be prospected from Titanium Ore

I prospected 21 stacks of Titanium Ore and received 58 units of Titanium Powder

here is a link:
http://www.wowhead.com/item=46849/titanium-powder#comments

**Comment by Zerixx** [comment]
"Added in patch 3.2.0.10026"
