### ISSUE TITLE
Silvermoon Guardian Aggro

### ISSUE THREAD

**Issue by mengh3** [FeenixServerProject/Wrath_3.3.5_Issue_tracker#6]
The Silvermoon Guardian patrolling in the Ruins of Silvermoon will attack any nearby enemy immediately after killing its current target, rather than running back to it's patrol path first. This sometimes leads to the npc carving a path of carnage through the poor wretches.

**Comment by lajhar** [comment]
Followed him for 3-4 routes, but he had only 1-2 single target / round all the time, I didn't see his killing spree, he didn't have a 2nd target to go for, reseted properly ad continued his route.
I think we can live with this issue if it exists.
