### ISSUE TITLE
Azjol-Nerub 2nd boss.

### ISSUE THREAD

**Issue by FRBooo** [FeenixServerProject/Wrath_3.3.5_Issue_tracker#60]
The boss got killed by the add packs coming down, way to fast. I think he got killed after 1,5mins without the elite packs spawning on the web ( We did not even activate the event i think). The group i was in tried to skip, but the guy was already dead when we got down there.

Can't really say much about how it happened, i think the waves may have started way before we finished the first boss.

**Comment by Zerixx** [comment]
Duplicate.
