### ISSUE TITLE
Caster off-hands missing from arena vendor

### ISSUE THREAD

**Issue by madsoigard** [FeenixServerProject/Wrath_3.3.5_Issue_tracker#61]
Title

**Comment by lajhar** [comment]
Items missing:

- Deadly Gladiator's Grimoire (42537)
- Deadly Gladiator's Reprieve (42531)
- Deadly Gladiator's Endgame (42525)

They can be purasched for **1350 arena points** if the player has at least **1930 personal and team arena rating**.

Items sold by the following NPCs:

- Kezzik the Striker (32405) in Area 52
- Argex Irongut (32407) in Gadgetzan
- Nargle Lashcord (31863) in Dalaran, Underbelly

**Comment by Zerixx** [comment]
Fixed on PreLive.
