### ISSUE TITLE
Quest  [Dragonmaw Race: Wing Commander Ichman]

### ISSUE THREAD

**Issue by Holmenros** [FeenixServerProject/Wrath_3.3.5_Issue_tracker#62]
He fades away randomly even tho u are close and not to far away.
The fire shots he threw away knocks you off ur mount even tho ur not even close to be hit.

**Comment by Zerixx** [comment]
I've not ever done this quest, but Wowhead say this:

> Added in patch 3.3.0.10772 

If this is true, any content added in the patches after 3.0.8 are automatically re-enabled once we change the content patch.
