### ISSUE TITLE
Amanitar's Mushrooms cannot be targeted

### ISSUE THREAD

**Issue by corcaroli** [FeenixServerProject/Wrath_3.3.5_Issue_tracker#64]
Amanitar, the optional boss in the heroic version of Ahn'Kahet 5 man dungeon, currently is nearly impossible to kill.
The key to this encounter are Healthy Mushrooms, which he is spawning throughout the fight. Upon killing those mushrooms release Potent Fungus that remove the Mini debuff, which reduces players' damage done by 75% and defence stat by 500.
The problem is that these mushrooms are currently cannot be targeted and thus killed, resulting in players having the Mini debuff for the whole duration of the fight. This means that probably the only way to kill the boss(as i heard from other players, who successfully did it) is to have a warlock in the group who spams Fear ability on the boss while the rest party damages the boss(with their damaged done reduced by 75%! Imagine how much time this takes).

Hoping for a quick fix, since this is the only boss for me(and probably for some other players too) left to kill for achievements [Heroic: Ahn'kahet: The Old Kingdom] and [Northrend Dungeon Hero]. :-D

The complete information about the encounter can be found here:
http://wow.gamepedia.com/Amanitar
http://wowwiki.wikia.com/wiki/Amanitar

**Comment by Zerixx** [comment]
Fix on PreLive
