### ISSUE TITLE
Malygos Phase 2 Disks

### ISSUE THREAD

**Issue by mengh3** [FeenixServerProject/Wrath_3.3.5_Issue_tracker#65]
During phase 2 of the fight, players that mount the disks dropped by the NPCs should not take any damage from Malygos. ( http://wowwiki.wikia.com/wiki/Malygos_(tactics) )

Currently, players on the disks take full damage from Malygos, making it extremely difficult to keep them alive during the fight.

**Comment by Zerixx** [comment]
@mengh3 or anyone here looking at this.. which spells should you be immune to when on the hover disc? I currently have it marked down as SPELL_ARCANE_OVERLOAD_DMG (56431) && SPELL_SURGE_OF_POWER_DMG (56548).

Thanks again for the report!

**Comment by Zerixx** [comment]
Fix on Pre-Live
