### ISSUE TITLE
Worshipers Immune to Mind Control in Grand Widow Faerlina 25 Man Fight

### ISSUE THREAD

**Issue by mengh3** [FeenixServerProject/Wrath_3.3.5_Issue_tracker#66]
In the 25 man version of this fight, Grand Widow Faerlina's Frenzy is supposed to be dispelled by mind controlling a worshiper, and using its ability Widow's Embrace near her. 
( http://wowwiki.wikia.com/wiki/Grand_Widow_Faerlina )

Currently the worshipers are immune to mind control, making it impossible to dispel Frenzy.

**Comment by Zerixx** [comment]
Fixed on PreLive.
