### ISSUE TITLE
[Druid] [Rogue] Shred/backstab not hitting through deterrence

### ISSUE THREAD

**Issue by Isuel** [FeenixServerProject/Wrath_3.3.5_Issue_tracker#69]
Currently, hunters are parrying shreds while their deterrence is up, which is something they shouldn't be able to do.

**Comment by Zerixx** [comment]
You're right. It shouldn't.. after some digging I found this:

http://www.arenajunkies.com/topic/119512-why-does-shred-go-through-deterrence/

Looks like the spell was bugged in WotLK. Not much I can do about that :/
