### ISSUE TITLE
Patchwerk in Naxx isn't scripted properly with his hateful strikes.

### ISSUE THREAD

**Issue by Yuskia** [FeenixServerProject/Wrath_3.3.5_Issue_tracker#71]
Apparently from what I've been told, this is actually an issue with every wrath private server that's on the Trinity base, but it should still be fixed.

Currently, patchwerk will hateful strike whoever is second highest HP, forcing you to have to dip into the oozes. That is not how this fight is supposed to work, this isn't Supremus.  It has a check system in place:
1) They must be in melee range
2) They must be less than first in threat but at least second or third in threat (25 man, only 2nd for 10 man)
3) The target must have the highest health of all targets available.

Currently, it seems that #2 is being ignored, as when our offtank on patchwerk would dip low from a hateful, if he wasn't topped off in time we would lose melee dps. This should never happen unless your hateful tank either dies or dips below on threat.

I went back through an internet archive to the old EJ forums on the naxx release thread and took a screenshot of this conversation with two different people both from highly respected guilds. Phoenix on Greymane was US 24th world 52 and Elitist jerks was US 44 world 99.

http://i.imgur.com/zJcYjs0.png

^Screen shot of the thread.

**Comment by Zerixx** [comment]
Fix on Pre-Live
