### ISSUE TITLE
Quest [Fervor of the Frostborn] - in The Storm Peak

### ISSUE THREAD

**Issue by Eagledrop** [FeenixServerProject/Wrath_3.3.5_Issue_tracker#72]
When talking to Fjorlin Frostbow in Frosthold, I can interact with him as expected and choose to be tested. 

When I press that I'm to be tested a gryphon appears, where a rider jumps ontop of it and I can't jump onto the gryphon as well, I just get a normal NPC speak window instead.

![image](https://cloud.githubusercontent.com/assets/4215133/22801507/6138b940-ef0d-11e6-8c75-04f18c43bd50.png)

This means that I can only get to The Iron Watcher, by flying myself and I can't use the abillities of the gryphon.

**Comment by Zerixx** [comment]
http://www.wowhead.com/quest=12874/fervor-of-the-frostborn

> Added in patch 3.3.0.10772

Coming soon.
