### ISSUE TITLE
[Raid] Gluth running towards back of room to eat zombies after Decimate.

### ISSUE THREAD

**Issue by Twoformirth** [FeenixServerProject/Wrath_3.3.5_Issue_tracker#73]
Gluth is currently turning around and running towards approaching zombies (post-Decimate) as soon as they leave the back-most area of the room (where the grates are).  If the zombies are kept entirely in the very back of the room (where the grates are), he won't do this, but as soon as the zombies start running towards him, the way they're supposed to, he runs halfway to the back of the room to reach them and eats them there.  He is currently meeting the zombies in the middle as they run to him, but he should only be turning around to consume zombies once THEY reach HIM, i.e. roughly melee range of him.

**Comment by Zerixx** [comment]
Fix on Pre-Live
