### ISSUE TITLE
Onslaught Gryphon Riders doing funky stuff

### ISSUE THREAD

**Issue by dangreenberggit** [FeenixServerProject/Wrath_3.3.5_Issue_tracker#75]
Onslaught Gryphon Riders (29333) in Onslaught Harbor are acting bizarrely: sometimes in the water, the aggro range seems to be very long, and they shoot through the mountain, etc.

**Comment by Zerixx** [comment]
Aggro range is a general issue on the server. However, I've applied a fix to our test realm and we'll see what happens ^^

**Comment by Zerixx** [comment]
Fix on Pre-Live

**Comment by FRBooo** [comment]
It seems they also fly through the towers, mountains.
