### ISSUE TITLE
Epic Northrend gems are still available even though they shouldn't until 3.2.0

### ISSUE THREAD

**Issue by corcaroli** [FeenixServerProject/Wrath_3.3.5_Issue_tracker#76]
New epic quality gems(i.e. Cardinal Ruby, Ametrince, etc.) were officially introduced in patch 3.2.0 only (here's some [proof](http://ptr.wowhead.com/item=36919/cardinal-ruby#comments:id=760851) from wowhead). Although they were removed from the Emblem of Heroism vendors, it is still possible to obtain them through one of the following ways: 

- prospecting Titanium Ore;
- creating by an alchemical transmutation;
- sometimes finding these inside an Icy Prism created by a jewelcrafter;
- exchanging for 10,000 honor points from Captain O'Neal in Stormwind or Lady Palanseer in Orgrimmar.

(I don't know if the last one was fixed together with the emblem vendors since i'm not a PvP player, so I listed it here just in case.)

You might want to look into this issue since you guys refuse to fix fishing dailies which came in the patch 3.1.0.

**Comment by Zerixx** [comment]
Fixed on PreLive.
