### ISSUE TITLE
NPCs Sometimes Face Opposite Direction [YUGE]

### ISSUE THREAD

**Issue by dangreenberggit** [FeenixServerProject/Wrath_3.3.5_Issue_tracker#77]
NPCs occasionally visually face the opposite direction of their attack. This can be not only confusing in certain situations and detrimental when bosses have cone attacks, but also an impediment to damage-dealers who rely heavily (or sometimes almost exclusively) on attacking from behind that severely effects gameplay.

**Comment by Zerixx** [comment]
Changes made to combat range/direction on Pre Live
