### ISSUE TITLE
"Bugged" Gathering Nodes

### ISSUE THREAD

**Issue by dangreenberggit** [FeenixServerProject/Wrath_3.3.5_Issue_tracker#79]
Many gathering nodes are unable to be looted. The gathering works and the loot in the loot window pops up, but that's as far as the process goes and the items can't be looted.

**Comment by Zerixx** [comment]
Consider this. You're in a phased zone. If someone tags the same node as you in a different phase, this will happen. May not be the issue, but do consider it a possibility. A likely one, at that.

**Comment by dangreenberggit** [comment]
I noticed it the most in Duskwood, recently. It could be a partial explanation, though.

**Comment by dangreenberggit** [comment]
I think it involves being in a group with loot rules. Might just be the original looter having ML on (regardless of threshold).

**Comment by Donlund** [comment]
If you are in a raid group, you are unable to loot mining nodes aswell I've noticed. So could be that its related to loot settings in your raid/party.
