### ISSUE TITLE
Paladin mounts are affected by haste

### ISSUE THREAD

**Issue by mengh3** [FeenixServerProject/Wrath_3.3.5_Issue_tracker#8]
Cast time for paladin's Summon Charger and Summon Warhorse are reduced by haste.

**Comment by deathstreal** [comment]
Paladin and Warlock mounts Cast time should be affected by Haste in WotLK, they are Spells.

**Comment by Zerixx** [comment]
I believe @deathstreal is correct here. That is working as it should.
