### ISSUE TITLE
[Quest] Tirion's Gambit

### ISSUE THREAD

**Issue by Kalasen12** [FeenixServerProject/Wrath_3.3.5_Issue_tracker#83]
After you have collected a Cultist Acolyte's Hood you are supposed to meet Tirion Fordring outside the Cathedral of Darkness but he is lying on the floor inside at the end of the Cathedral and you can't finish the quest.
I have cleared my cache twice and retaken the quest, same result.

Thanks

**Comment by Zerixx** [comment]
http://www.wowhead.com/quest=13403/tirions-gambit
http://www.wowhead.com/quest=13364/tirions-gambit

> Added in patch 3.3.0.10958

Coming then.
