### ISSUE TITLE
Orc Death Knight don't get expertise from wearing axes.

### ISSUE THREAD

**Issue by fyrinx** [FeenixServerProject/Wrath_3.3.5_Issue_tracker#84]
As stated in the title. Orc racial Axe Specialization seem to be bugged when it comes to DK. What it should do is to add 5 expertise if the orc is wearing the axe or "the hand" of the axe.

**Comment by dangreenberggit** [comment]
I was unable to replicate this issue. Axe weapons appear to give Orcs 5 expertise as intended. While removing an axe weapon and being unarmed does not remove 5 expertise on the character sheet, equipping a non-axe weapon will lower expertise by 5. Expertise is also correctly applying to specific "hands" when dual-wielding and equipping a 1H axe.

**Comment by fyrinx** [comment]
Yea, you are right. I recently tested it and it seemed to work, might have gotten fixed. My apologies for this topic.
