### ISSUE TITLE
[Raid] Phase 2 "dance" begins too soon after Heigan teleports onto the platform.

### ISSUE THREAD

**Issue by Twoformirth** [FeenixServerProject/Wrath_3.3.5_Issue_tracker#85]
Currently, the "dance" (or slime wall spawn pattern) begins about 4.5 seconds after Heigan has teleported onto the platform.  However, on retail, the dance began about 8.5 seconds after Heigan teleported, giving the tank/melee time to get into their "start" position.  See: https://youtu.be/VUlliMso570?t=2m40s for retail timing.

I recorded a video of me doing the fight so you can see how quickly this occurs.  See: https://youtu.be/FlREWbHrVsY.  By the time I reach the "start" position, the first slime wall has already popped up.  I compensate for this in the video by starting to run down from the platform early, but the melee all get hit because they didn't quite reach the "start" position before the first phase 2 wall popped.

You can even compare the time until Heigan returns on each of our videos to see the difference.  The time until Heigan returns starts at 47 seconds.  On the TankSpot video, the first wall doesn't pop until about 38.5 seconds remaining.  On my video, the first wall pops at about 42.5 seconds remaining.

**Comment by Zerixx** [comment]
Fix on PreLive
