### ISSUE TITLE
Uncommon pvp gem recipes missings

### ISSUE THREAD

**Issue by niggerious** [FeenixServerProject/Wrath_3.3.5_Issue_tracker#87]
In Alliance side Captain O'Neal <Jewelcrafting Quartermaster> got deleted because he sold raw epic gems,
now we can't ge access to the uncommon pvp gem recipes. (Added in patch 3.0.2.8962)
I don't know about Horde side, but i'm guessing the issues is the same there.
(Horde NPC: Lady Palanseer <Jewelcrafting Quartermaster>)

Missing recipes:
Design: Durable Huge Citrine
Design: Empowered Huge Citrine
Design: Lucent Huge Citrine
Design: Mysterious Shadow Crystal
Design: Mystic Sun Crystal
Design: Opaque Dark Jade
Design: Resplendent Huge Citrine
Design: Shattered Dark Jade
Design: Steady Dark Jade
Design: Stormy Chalcedony
Design: Tense Dark Jade
Design: Turbid Dark Jade

**Comment by Zerixx** [comment]
http://www.wowhead.com/quest=13168/parting-gifts

> Added in patch 3.3.0.10958

Coming then.

**Comment by niggerious** [comment]
???

**Comment by Zerixx** [comment]
@niggerious  I posted a response and closed the wrong issue. Don't worry ^^

**Comment by Holmenros** [comment]
Aswell as Design: Bold Cardinal Ruby from Timothy Johnson

**Comment by niggerious** [comment]
So, will it be fixed?
Or don't need to be fixed?

**Comment by Zerixx** [comment]
This will be fixed very soon. No worries :)

**Comment by Zerixx** [comment]
Fixed on PreLive.

**Comment by niggerious** [comment]
the alliance NPC is still missing
