### ISSUE TITLE
[Quest] Unable to Do "Mission: Gateways Murketh and Shaadraz" Due to Incorrect NPC Position

### ISSUE THREAD

**Issue by dangreenberggit** [FeenixServerProject/Wrath_3.3.5_Issue_tracker#89]
Quest "Mission: Gateways Murketh and Shaadraz" (10129) cannot be completed.  Wing Commander Brack, is supposed to initiate the bombing run, does not do so. When clicking the appropriate dialogue statement, an error message appears: "You are too far away from the taxi stand!"

[Edit: for those attempting the quest, it appears the error message is based on player position and not NPC position, and standing closer to the wyverns will allow the player to initiate the bombing run.]

It appears the NPC is not in his proper position. Image of proper position here: 
![image](https://cloud.githubusercontent.com/assets/7952671/22865922/24a88832-f176-11e6-8341-f17c14d0ac31.png)

Edit again: to repeat, the image above is of the proper position. When the issue was encountered, the NPC was *not* in that position. Therefore if the NPC returns to an improper position again, the issue will return.

**Comment by lajhar** [comment]
No issue found on the PTR.
The NPC stands at the exact same place as your picture shows.
I could start the trip even from maxrange
