### ISSUE TITLE
[Raid] Power Sparks are porting to Malygos and being consumed by him.

### ISSUE THREAD

**Issue by Twoformirth** [FeenixServerProject/Wrath_3.3.5_Issue_tracker#91]
Sparks start to descend onto the platform normally, but shortly after arriving they "port" or "blink" to the centre of Malygos' hitbox and he consumes them.  They do not gradually move across the platform to him, nor do they move at an accelerated speed.  They simply move about halfway to him (at an appropriate speed) and then blink out of sight, only to reappear right under him.  Even when rooting, the root instantly breaks and the spark teleports to Malygos.  I asked someone else whose group used a DK to grip the sparks when they were just reaching the platform, and they did manage to kill them and get the buff, but if you don't kill the spark very far away from Malygos, it will teleport to him and he will eat it.

See: https://youtu.be/25KVkWK8d0E

**Comment by Zerixx** [comment]
Already reported and fixed. Coming to live soon.
