### ISSUE TITLE
[Raid] Surge of Power on Malygos is doing far less damage than it is supposed to.

### ISSUE THREAD

**Issue by Twoformirth** [FeenixServerProject/Wrath_3.3.5_Issue_tracker#93]
I did not use my Flame Shield and only took 25,000 damage from one instance of Surge of Power.  Sources indicate that it was more like ~70-75K damage dealt over three seconds on retail.  You are supposed to have to use your Flame Shield to mitigate at least a portion of this damage to avoid death.

http://www.wowhead.com/spell=57407/surge-of-power
http://www.worldofstrats.com/Malygos/tabid/127/Default.aspx

**Comment by Zerixx** [comment]
![image](https://cloud.githubusercontent.com/assets/4999313/22898490/8246c89e-f1f5-11e6-957c-996a47c4fada.png)

Notice the 72k damage taken from Surge.

**Comment by Zerixx** [comment]
Did my tests on 25 and 10. Definitely doing the proper damage.

**Comment by Twoformirth** [comment]
I see...  I only got Surge of Power once during the fight and I did not shield, and on both Recount and Skada it said I took 25K damage from it.  I also checked other people's damage and 25K was the norm.  Not sure why that would be.
