### ISSUE TITLE
Item [Tears of Bitter Anguish]

### ISSUE THREAD

**Issue by Holmenros** [FeenixServerProject/Wrath_3.3.5_Issue_tracker#95]
Yes I know the droprate is lower then 1%

But I want to make sure you have implemented the item because
I haven't seen it on AH or anyone wearing it yet.

I have killcount on 4k+ on them atm and I also wonder if  "progressive percentages" on droprate
is implemented. 

http://wow.gamepedia.com/Tears_of_Bitter_Anguish
http://www.sk-gaming.com/content/23182-Wotlk_uses_Warcraft_3_codes_for_item_drop_rate
http://www.shacknews.com/article/57886/blizzard-details-secret-world-of

Kind regards Holmes

**Comment by corcaroli** [comment]
I've seen it a couple of times on AH.

**Comment by Zerixx** [comment]
It's actually been on the AH 7 times :)

**Comment by Holmenros** [comment]
"progressive percentages"  ? can you answer that aswell?
