### ISSUE TITLE
Sartharion + X Drakes Encounter

### ISSUE THREAD

**Issue by deathstreal** [FeenixServerProject/Wrath_3.3.5_Issue_tracker#96]
http://wowwiki.wikia.com/wiki/Sartharion
-Fire Breath - Inflicts 8750 to 11250 (10938 to 14062 Heroic) Fire damage to enemies in a cone in front of the caster. 
Bug: This still does the same damage even with: Power of Shadron - Shadron's presence increases fire damage taken increased by 100%. Active only while fighting Sartharion.
-Vesperon's portal contains a disciple who increases Fire and Shadow damage taken by 75% and puts Twilight Torment on the raid, making them damage themselves when attacking. 
Bug: There are currently 3 Disciples in Vesperon's portal if part of Sartharion's encounter. Not sure if it is 1 or 3 when fought separately. There is a chance Vesperon's portal merges with Shadron's, which is not supposed to happen.
Bug2: Twilight Torment kills the raid when clicking the Portal.
I might be forgetting one more, I will edit the post accordingly if that's the case.

**Comment by lajhar** [comment]
On the PTR:
- Fire Breath damage is increased by 100% when the Power of Shadron is active as intended
- Twilight Torment didn't kill me when clicked on the Portal

Not sure about the 2nd.
