### ISSUE TITLE
Jeeves Recipe + froststeel tube not dropping from salvaging

### ISSUE THREAD

**Issue by ArcaneHymn** [FeenixServerProject/Wrath_3.3.5_Issue_tracker#97]
Greetings!

The Jeeves recipe and Froststeel tube doesn't seem to drop at all when you salvage Library guardian mobs. The recipe has 1% chance to drop, while the tube has 0.5% chance. I killed so many of them that I found 5 + overcharged capacitor which also has 0.5% drop rate, and tons of  volatile blasting triggers and handful of cobalt bolts. Please fix! :D

https://wotlk-twinhead.twinstar.cz/?npc=29724#skinningsalvaging

**Comment by Dzejrou** [comment]
Jeeves was added in 3.2.0, [source](http://wowwiki.wikia.com/wiki/Jeeves).

**Comment by ArcaneHymn** [comment]
Wormhole Generator was added in 3.2.0 too , yet its available

**Comment by Zerixx** [comment]
Some things were left out due to difficulty of gating them. Typically, and generally, if something was added in within the 3.X <-- version of a a patch it's gated with some exceptions for obvious reasons.

**Comment by ArcaneHymn** [comment]
So you're saying that Jeeves recipe wont be available for a long time? Also, what about froststeel tube? thats a very core item.

**Comment by lulzies** [comment]
Jeeves recipe exists in the game at the moment. I got it by salvaging an Oculus construct.

Proof: http://imgur.com/a/2ImUW

As reported earlier though Jeeves only provides banks access. He should be able to provide repair and reagents

**Comment by Zerixx** [comment]
This may be, but the script for jeeves won't activate until 3.2 then.
