### ISSUE TITLE
Gotura Fourwinds not existent ( not where hes supposed to be)

### ISSUE THREAD

**Issue by Nekrum9** [FeenixServerProject/Wrath_3.3.5_Issue_tracker#98]
for completing the quest : "Relic of the Earthen ring",  you need to speak to Gotura, who is sadly not present where indicated on the map. Since this quest makes it so we can combine all four of the shamans totem into one, it free up a lot of space in our inventory, and it would be really appreciated has to why i dont have acces/see this NPC

thank you in advance for your support

**Comment by Zerixx** [comment]
3.3.5 content.

**Comment by Nekrum9** [comment]
then why is the quest available? and i am currently playing what its says here has the : 3.3.5a Version.
Why make the quest available if not the reward for it? im just confused

**Comment by Zerixx** [comment]
> Some things were left out due to difficulty of gating them. Typically, and generally, if something was added in within the 3.X <-- version of a a patch it's gated with some exceptions for obvious reasons.
