### ISSUE TITLE
Leave no one behind.

### ISSUE THREAD

**Issue by FRBooo** [FeenixServerProject/Wrath_3.3.5_Issue_tracker#99]
I figured it is not proper by seing a couple of the npc's scattered on the wrong places.

First of u can't go and deliver the crusaders 1 by 1.
I also found Crusader Josephine on the wrong location, in adition i could not ress her on the location i did find her.
Jonathan did simpy not allow me to bandage him.
Lamoof was possible to bandage, but it was not possible to deliver him alone.

**Comment by lajhar** [comment]
I've just done this quest on live and PTR aswell, the only issue I encountered with that Crusader Josephine (28143) did not disappear/despawn when he bleeded to death, instead she kept following me. However, the quest was easily doable with this minor issue.
